# Generated by Django 4.2.25 on 2025-10-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_schedule_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.TextField(blank=True),
        ),
    ]
