# Generated by Django 4.2.25 on 2025-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id_categoria_servicio', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoProfesional',
            fields=[
                ('id_documento_profesional', models.UUIDField(primary_key=True, serialize=False)),
                ('id_perfil_profesional', models.UUIDField()),
                ('id_servicio_profesional', models.UUIDField(null=True)),
                ('tipo_documento', models.CharField(max_length=30)),
                ('nombre_documento', models.CharField(max_length=200)),
                ('url_archivo', models.TextField()),
                ('estado_verificacion', models.CharField(max_length=20)),
                ('rut_verificador', models.CharField(max_length=12, null=True)),
                ('verificado_en', models.DateTimeField(null=True)),
                ('subido_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'documento_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id_perfil_profesional', models.UUIDField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=12)),
                ('descripcion_general', models.TextField()),
                ('estado_verificacion_general', models.CharField(max_length=20)),
                ('rut_verificador', models.CharField(max_length=12, null=True)),
                ('verificado_en', models.DateTimeField(null=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfil_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioProfesional',
            fields=[
                ('id_servicio_profesional', models.UUIDField(primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(max_length=12)),
                ('id_categoria_servicio', models.UUIDField()),
                ('anos_experiencia', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('tipo_duracion', models.CharField(max_length=10)),
                ('duracion_fija_minutos', models.IntegerField(null=True)),
                ('duracion_minima_minutos', models.IntegerField(null=True)),
                ('duracion_maxima_minutos', models.IntegerField(null=True)),
                ('precio_fijo', models.IntegerField()),
                ('estado_verificacion', models.CharField(max_length=20)),
                ('es_primer_servicio', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'servicio_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioDominio',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hash_contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('id_comuna', models.UUIDField()),
                ('direccion', models.TextField()),
                ('rol', models.CharField(default='cliente', max_length=20)),
                ('foto_perfil_url', models.TextField(null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('telefono_verificado', models.BooleanField(default=False)),
                ('perfil_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField()),
                ('actualizado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceVisibility',
            fields=[
                ('service_id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_service_visibility',
            },
        ),
    ]
